# Generated by Django 3.2.6 on 2021-08-27 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [("users", "0001_initial"), ("bookings", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="driverad",
            name="acceptor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accepted_ads",
                to="users.customer",
            ),
        ),
        migrations.AddField(
            model_name="driverad",
            name="poster",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posted_ads",
                to="users.driver",
            ),
        ),
        migrations.AddField(
            model_name="customerad",
            name="acceptor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accepted_ads",
                to="users.driver",
            ),
        ),
        migrations.AddField(
            model_name="customerad",
            name="poster",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posted_ads",
                to="users.customer",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="customer_ad",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bookings.customerad",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="driver_ad",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bookings.driverad",
            ),
        ),
    ]
