# Generated by Django 3.2.7 on 2021-09-23 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("users", "0004_auto_20210921_2001"), ("bookings", "0002_initial")]

    operations = [
        migrations.AlterField(
            model_name="customerad",
            name="acceptor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accepted_ads",
                to="users.driver",
            ),
        ),
        migrations.AlterField(
            model_name="customerad",
            name="description",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="customerad",
            name="poster",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posted_ads",
                to="users.customer",
            ),
        ),
        migrations.AlterField(
            model_name="driverad",
            name="description",
            field=models.CharField(default="", max_length=255),
        ),
    ]
