# Generated by Django 3.2.7 on 2021-09-26 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("bookings", "0003_auto_20210923_0930")]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="driver_ad",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="bookings.driverad",
            ),
        )
    ]
