# Generated by Django 3.2.7 on 2021-09-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("bookings", "0004_alter_booking_driver_ad")]

    operations = [
        migrations.AddField(
            model_name="driverad",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="driverad",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
