# Generated by Django 3.2.7 on 2021-09-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("bookings", "0005_auto_20210926_1005")]

    operations = [
        migrations.RemoveField(model_name="booking", name="end_time"),
        migrations.RemoveField(model_name="booking", name="start_time"),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("P", "Pending"),
                    ("A", "Accepted"),
                    ("D", "Dispatched"),
                    ("F", "Fulfilled"),
                ],
                default="P",
                max_length=1,
            ),
        ),
    ]
