# Generated by Django 3.2.7 on 2021-09-28 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210923_1100'),
        ('bookings', '0007_alter_driverad_acceptor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bookings.booking')),
            ],
        ),
        migrations.CreateModel(
            name='DriverAdBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(default='', max_length=1000)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='bookings.driverad')),
                ('bidder', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_ads', to='users.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAdBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(default='', max_length=1000)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='bookings.customerad')),
                ('bidder', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_ads', to='users.driver')),
            ],
        ),
    ]
