# Generated by Django 3.2.7 on 2021-09-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_customeradbid_driveradbid_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeradbid',
            name='is_accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driveradbid',
            name='is_accepted',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
