# Generated by Django 3.2.7 on 2021-09-28 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
        ('bookings', '0009_auto_20210928_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverad',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='vehicles.vehicle'),
        ),
    ]
