# Generated by Django 3.2.7 on 2021-10-06 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_customeradbid_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_bid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.customeradbid'),
        ),
        migrations.AddField(
            model_name='booking',
            name='driver_bid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.driveradbid'),
        ),
    ]
