# Generated by Django 3.2.9 on 2021-11-26 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehiclecategory_image'),
        ('bookings', '0017_auto_20211125_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerad',
            name='vehicle_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehiclecategory'),
        ),
    ]
