# Generated by Django 3.2.9 on 2021-11-26 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehiclecategory_image'),
        ('bookings', '0018_customerad_vehicle_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerad',
            name='vehicle_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_ads', to='vehicles.vehiclecategory'),
        ),
    ]
