# Generated by Django 3.2.9 on 2021-12-12 16:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_alter_customerad_vehicle_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='created',
        ),
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_completed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
