# Generated by Django 3.2.9 on 2021-12-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0020_auto_20211212_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeradbid',
            name='is_accepted',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='driveradbid',
            name='is_accepted',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
