# Generated by Django 3.2.9 on 2021-12-19 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210923_1100'),
        ('bookings', '0021_auto_20211219_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='users.driver'),
        ),
    ]
