# Generated by Django 3.2.7 on 2021-09-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('C', 'New Customer Ad'), ('D', 'New Driver Ad'), ('A', 'Ad Accepted'), ('B', 'Bid Added'), ('G', 'Global System-wide ')], max_length=1),
        ),
    ]
