# Generated by Django 3.2.11 on 2022-02-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('C', 'New Customer Ad'), ('D', 'New Driver Ad'), ('A', 'Ad Accepted'), ('B', 'Bid Added'), ('K', 'Booking'), ('G', 'Global System-wide ')], max_length=1),
        ),
    ]
