name: workflow-test

on:
  push:
    branches:
      - master
      - main

jobs:
  ecr-push-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.EC2_REGION }}

      - name: login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - uses: actions/checkout@v2
      - name: Build and push immage to ECR
        env:
          ECR_WEB_IMAGE: ${{ secrets.ECR_WEB_IMAGE }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          echo $(ls app)
          docker-compose build
          docker-compose push

      - uses: actions/checkout@v2
      - name: build
        run: ./.github/scripts/build.sh
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USER: ${{ secrets.SSH_USER }}
          EC2_PUBLIC_IP_ADDRESS: ${{ secrets.EC2_PUBLIC_IP_ADDRESS }}
          ECR_WEB_IMAGE: ${{ secrets.ECR_WEB_IMAGE }}
          ECR_USER: ${{ secrets.ECR_USER }}
          EC2_REGION: ${{ secrets.EC2_REGION }}
